#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/*
 *main - checks if the random number is positiver or negative
 *@n - random integer generated by std library
 * Return - return 0
 */
int main(void)
{
	int n;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	if (n > 0)
	{
		printf("%d is positive\n", n);
	}
	else if (n == 0)
	{
		printf("%d is zero\n", n);
	}
	else
	{
		printf("%d is negative\n", n);
	}
	return (0);
}
