#include <stdlib.h>
#include <time.h>
#include <stdio.h>
/*
 * main - prints whether the number is posetive or negative
 *@n-random number generated by standard library
 * return  - return 0 to operating system
 */
int main(void)
{
	int n;

	srand(time(0));
	n = rand() - RAND_MAX / 2;
	if (n > 0)
	{
		printf(" %d is positive", n);
	}
	else if (n < 0)
	{
		printf("%d is negative", n);
	}
	else
	{
		printf("%d is zero", n);
	}
	return (0);
}
